// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Archiver is an autogenerated mock type for the Archiver type
type Archiver struct {
	mock.Mock
}

type Archiver_Expecter struct {
	mock *mock.Mock
}

func (_m *Archiver) EXPECT() *Archiver_Expecter {
	return &Archiver_Expecter{mock: &_m.Mock}
}

// ArchiveDir provides a mock function with given fields: zipPath, srcDir
func (_m *Archiver) ArchiveDir(zipPath string, srcDir string) error {
	ret := _m.Called(zipPath, srcDir)

	if len(ret) == 0 {
		panic("no return value specified for ArchiveDir")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(zipPath, srcDir)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Archiver_ArchiveDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArchiveDir'
type Archiver_ArchiveDir_Call struct {
	*mock.Call
}

// ArchiveDir is a helper method to define mock.On call
//   - zipPath string
//   - srcDir string
func (_e *Archiver_Expecter) ArchiveDir(zipPath interface{}, srcDir interface{}) *Archiver_ArchiveDir_Call {
	return &Archiver_ArchiveDir_Call{Call: _e.mock.On("ArchiveDir", zipPath, srcDir)}
}

func (_c *Archiver_ArchiveDir_Call) Run(run func(zipPath string, srcDir string)) *Archiver_ArchiveDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Archiver_ArchiveDir_Call) Return(_a0 error) *Archiver_ArchiveDir_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Archiver_ArchiveDir_Call) RunAndReturn(run func(string, string) error) *Archiver_ArchiveDir_Call {
	_c.Call.Return(run)
	return _c
}

// ArchiveFiles provides a mock function with given fields: zipPath, baseDir, files
func (_m *Archiver) ArchiveFiles(zipPath string, baseDir string, files []string) error {
	ret := _m.Called(zipPath, baseDir, files)

	if len(ret) == 0 {
		panic("no return value specified for ArchiveFiles")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, []string) error); ok {
		r0 = rf(zipPath, baseDir, files)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Archiver_ArchiveFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArchiveFiles'
type Archiver_ArchiveFiles_Call struct {
	*mock.Call
}

// ArchiveFiles is a helper method to define mock.On call
//   - zipPath string
//   - baseDir string
//   - files []string
func (_e *Archiver_Expecter) ArchiveFiles(zipPath interface{}, baseDir interface{}, files interface{}) *Archiver_ArchiveFiles_Call {
	return &Archiver_ArchiveFiles_Call{Call: _e.mock.On("ArchiveFiles", zipPath, baseDir, files)}
}

func (_c *Archiver_ArchiveFiles_Call) Run(run func(zipPath string, baseDir string, files []string)) *Archiver_ArchiveFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *Archiver_ArchiveFiles_Call) Return(_a0 error) *Archiver_ArchiveFiles_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Archiver_ArchiveFiles_Call) RunAndReturn(run func(string, string, []string) error) *Archiver_ArchiveFiles_Call {
	_c.Call.Return(run)
	return _c
}

// NewArchiver creates a new instance of Archiver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArchiver(t interface {
	mock.TestingT
	Cleanup(func())
}) *Archiver {
	mock := &Archiver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
