// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	semver "github.com/Masterminds/semver/v3"
	ports "github.com/UNSAReport/UNSAReport/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// ComponentRegistry is an autogenerated mock type for the ComponentRegistry type
type ComponentRegistry struct {
	mock.Mock
}

type ComponentRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *ComponentRegistry) EXPECT() *ComponentRegistry_Expecter {
	return &ComponentRegistry_Expecter{mock: &_m.Mock}
}

// FetchComponentFile provides a mock function with given fields: info, cv
func (_m *ComponentRegistry) FetchComponentFile(info ports.ComponentInfo, cv *ports.ComponentVersion) ([]byte, error) {
	ret := _m.Called(info, cv)

	if len(ret) == 0 {
		panic("no return value specified for FetchComponentFile")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(ports.ComponentInfo, *ports.ComponentVersion) ([]byte, error)); ok {
		return rf(info, cv)
	}
	if rf, ok := ret.Get(0).(func(ports.ComponentInfo, *ports.ComponentVersion) []byte); ok {
		r0 = rf(info, cv)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(ports.ComponentInfo, *ports.ComponentVersion) error); ok {
		r1 = rf(info, cv)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ComponentRegistry_FetchComponentFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchComponentFile'
type ComponentRegistry_FetchComponentFile_Call struct {
	*mock.Call
}

// FetchComponentFile is a helper method to define mock.On call
//   - info ports.ComponentInfo
//   - cv *ports.ComponentVersion
func (_e *ComponentRegistry_Expecter) FetchComponentFile(info interface{}, cv interface{}) *ComponentRegistry_FetchComponentFile_Call {
	return &ComponentRegistry_FetchComponentFile_Call{Call: _e.mock.On("FetchComponentFile", info, cv)}
}

func (_c *ComponentRegistry_FetchComponentFile_Call) Run(run func(info ports.ComponentInfo, cv *ports.ComponentVersion)) *ComponentRegistry_FetchComponentFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ports.ComponentInfo), args[1].(*ports.ComponentVersion))
	})
	return _c
}

func (_c *ComponentRegistry_FetchComponentFile_Call) Return(_a0 []byte, _a1 error) *ComponentRegistry_FetchComponentFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ComponentRegistry_FetchComponentFile_Call) RunAndReturn(run func(ports.ComponentInfo, *ports.ComponentVersion) ([]byte, error)) *ComponentRegistry_FetchComponentFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetComponent provides a mock function with given fields: name
func (_m *ComponentRegistry) GetComponent(name string) (ports.ComponentInfo, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetComponent")
	}

	var r0 ports.ComponentInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (ports.ComponentInfo, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) ports.ComponentInfo); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(ports.ComponentInfo)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ComponentRegistry_GetComponent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComponent'
type ComponentRegistry_GetComponent_Call struct {
	*mock.Call
}

// GetComponent is a helper method to define mock.On call
//   - name string
func (_e *ComponentRegistry_Expecter) GetComponent(name interface{}) *ComponentRegistry_GetComponent_Call {
	return &ComponentRegistry_GetComponent_Call{Call: _e.mock.On("GetComponent", name)}
}

func (_c *ComponentRegistry_GetComponent_Call) Run(run func(name string)) *ComponentRegistry_GetComponent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ComponentRegistry_GetComponent_Call) Return(_a0 ports.ComponentInfo, _a1 error) *ComponentRegistry_GetComponent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ComponentRegistry_GetComponent_Call) RunAndReturn(run func(string) (ports.ComponentInfo, error)) *ComponentRegistry_GetComponent_Call {
	_c.Call.Return(run)
	return _c
}

// ListComponents provides a mock function with no fields
func (_m *ComponentRegistry) ListComponents() ([]ports.ComponentInfo, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListComponents")
	}

	var r0 []ports.ComponentInfo
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]ports.ComponentInfo, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []ports.ComponentInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.ComponentInfo)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ComponentRegistry_ListComponents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListComponents'
type ComponentRegistry_ListComponents_Call struct {
	*mock.Call
}

// ListComponents is a helper method to define mock.On call
func (_e *ComponentRegistry_Expecter) ListComponents() *ComponentRegistry_ListComponents_Call {
	return &ComponentRegistry_ListComponents_Call{Call: _e.mock.On("ListComponents")}
}

func (_c *ComponentRegistry_ListComponents_Call) Run(run func()) *ComponentRegistry_ListComponents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ComponentRegistry_ListComponents_Call) Return(_a0 []ports.ComponentInfo, _a1 error) *ComponentRegistry_ListComponents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ComponentRegistry_ListComponents_Call) RunAndReturn(run func() ([]ports.ComponentInfo, error)) *ComponentRegistry_ListComponents_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveVersion provides a mock function with given fields: name, rangeSpec
func (_m *ComponentRegistry) ResolveVersion(name string, rangeSpec string) (*semver.Version, *ports.ComponentInfo, *ports.ComponentVersion, error) {
	ret := _m.Called(name, rangeSpec)

	if len(ret) == 0 {
		panic("no return value specified for ResolveVersion")
	}

	var r0 *semver.Version
	var r1 *ports.ComponentInfo
	var r2 *ports.ComponentVersion
	var r3 error
	if rf, ok := ret.Get(0).(func(string, string) (*semver.Version, *ports.ComponentInfo, *ports.ComponentVersion, error)); ok {
		return rf(name, rangeSpec)
	}
	if rf, ok := ret.Get(0).(func(string, string) *semver.Version); ok {
		r0 = rf(name, rangeSpec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*semver.Version)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) *ports.ComponentInfo); ok {
		r1 = rf(name, rangeSpec)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*ports.ComponentInfo)
		}
	}

	if rf, ok := ret.Get(2).(func(string, string) *ports.ComponentVersion); ok {
		r2 = rf(name, rangeSpec)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*ports.ComponentVersion)
		}
	}

	if rf, ok := ret.Get(3).(func(string, string) error); ok {
		r3 = rf(name, rangeSpec)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// ComponentRegistry_ResolveVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveVersion'
type ComponentRegistry_ResolveVersion_Call struct {
	*mock.Call
}

// ResolveVersion is a helper method to define mock.On call
//   - name string
//   - rangeSpec string
func (_e *ComponentRegistry_Expecter) ResolveVersion(name interface{}, rangeSpec interface{}) *ComponentRegistry_ResolveVersion_Call {
	return &ComponentRegistry_ResolveVersion_Call{Call: _e.mock.On("ResolveVersion", name, rangeSpec)}
}

func (_c *ComponentRegistry_ResolveVersion_Call) Run(run func(name string, rangeSpec string)) *ComponentRegistry_ResolveVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *ComponentRegistry_ResolveVersion_Call) Return(_a0 *semver.Version, _a1 *ports.ComponentInfo, _a2 *ports.ComponentVersion, _a3 error) *ComponentRegistry_ResolveVersion_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *ComponentRegistry_ResolveVersion_Call) RunAndReturn(run func(string, string) (*semver.Version, *ports.ComponentInfo, *ports.ComponentVersion, error)) *ComponentRegistry_ResolveVersion_Call {
	_c.Call.Return(run)
	return _c
}

// NewComponentRegistry creates a new instance of ComponentRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewComponentRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *ComponentRegistry {
	mock := &ComponentRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
