// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	ports "github.com/UNSAReport/UNSAReport/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// ConfigStore is an autogenerated mock type for the ConfigStore type
type ConfigStore struct {
	mock.Mock
}

type ConfigStore_Expecter struct {
	mock *mock.Mock
}

func (_m *ConfigStore) EXPECT() *ConfigStore_Expecter {
	return &ConfigStore_Expecter{mock: &_m.Mock}
}

// FindProjectRoot provides a mock function with given fields: startDir
func (_m *ConfigStore) FindProjectRoot(startDir string) (string, ports.UnsareportConfig, bool, error) {
	ret := _m.Called(startDir)

	if len(ret) == 0 {
		panic("no return value specified for FindProjectRoot")
	}

	var r0 string
	var r1 ports.UnsareportConfig
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(string) (string, ports.UnsareportConfig, bool, error)); ok {
		return rf(startDir)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(startDir)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) ports.UnsareportConfig); ok {
		r1 = rf(startDir)
	} else {
		r1 = ret.Get(1).(ports.UnsareportConfig)
	}

	if rf, ok := ret.Get(2).(func(string) bool); ok {
		r2 = rf(startDir)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(string) error); ok {
		r3 = rf(startDir)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// ConfigStore_FindProjectRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindProjectRoot'
type ConfigStore_FindProjectRoot_Call struct {
	*mock.Call
}

// FindProjectRoot is a helper method to define mock.On call
//   - startDir string
func (_e *ConfigStore_Expecter) FindProjectRoot(startDir interface{}) *ConfigStore_FindProjectRoot_Call {
	return &ConfigStore_FindProjectRoot_Call{Call: _e.mock.On("FindProjectRoot", startDir)}
}

func (_c *ConfigStore_FindProjectRoot_Call) Run(run func(startDir string)) *ConfigStore_FindProjectRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ConfigStore_FindProjectRoot_Call) Return(projectRoot string, cfg ports.UnsareportConfig, ok bool, err error) *ConfigStore_FindProjectRoot_Call {
	_c.Call.Return(projectRoot, cfg, ok, err)
	return _c
}

func (_c *ConfigStore_FindProjectRoot_Call) RunAndReturn(run func(string) (string, ports.UnsareportConfig, bool, error)) *ConfigStore_FindProjectRoot_Call {
	_c.Call.Return(run)
	return _c
}

// ReadConfig provides a mock function with given fields: destDir
func (_m *ConfigStore) ReadConfig(destDir string) (ports.UnsareportConfig, bool, error) {
	ret := _m.Called(destDir)

	if len(ret) == 0 {
		panic("no return value specified for ReadConfig")
	}

	var r0 ports.UnsareportConfig
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (ports.UnsareportConfig, bool, error)); ok {
		return rf(destDir)
	}
	if rf, ok := ret.Get(0).(func(string) ports.UnsareportConfig); ok {
		r0 = rf(destDir)
	} else {
		r0 = ret.Get(0).(ports.UnsareportConfig)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(destDir)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(destDir)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ConfigStore_ReadConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadConfig'
type ConfigStore_ReadConfig_Call struct {
	*mock.Call
}

// ReadConfig is a helper method to define mock.On call
//   - destDir string
func (_e *ConfigStore_Expecter) ReadConfig(destDir interface{}) *ConfigStore_ReadConfig_Call {
	return &ConfigStore_ReadConfig_Call{Call: _e.mock.On("ReadConfig", destDir)}
}

func (_c *ConfigStore_ReadConfig_Call) Run(run func(destDir string)) *ConfigStore_ReadConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ConfigStore_ReadConfig_Call) Return(cfg ports.UnsareportConfig, ok bool, err error) *ConfigStore_ReadConfig_Call {
	_c.Call.Return(cfg, ok, err)
	return _c
}

func (_c *ConfigStore_ReadConfig_Call) RunAndReturn(run func(string) (ports.UnsareportConfig, bool, error)) *ConfigStore_ReadConfig_Call {
	_c.Call.Return(run)
	return _c
}

// ReadLockfile provides a mock function with given fields: destDir
func (_m *ConfigStore) ReadLockfile(destDir string) (ports.Lockfile, error) {
	ret := _m.Called(destDir)

	if len(ret) == 0 {
		panic("no return value specified for ReadLockfile")
	}

	var r0 ports.Lockfile
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (ports.Lockfile, error)); ok {
		return rf(destDir)
	}
	if rf, ok := ret.Get(0).(func(string) ports.Lockfile); ok {
		r0 = rf(destDir)
	} else {
		r0 = ret.Get(0).(ports.Lockfile)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(destDir)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConfigStore_ReadLockfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadLockfile'
type ConfigStore_ReadLockfile_Call struct {
	*mock.Call
}

// ReadLockfile is a helper method to define mock.On call
//   - destDir string
func (_e *ConfigStore_Expecter) ReadLockfile(destDir interface{}) *ConfigStore_ReadLockfile_Call {
	return &ConfigStore_ReadLockfile_Call{Call: _e.mock.On("ReadLockfile", destDir)}
}

func (_c *ConfigStore_ReadLockfile_Call) Run(run func(destDir string)) *ConfigStore_ReadLockfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ConfigStore_ReadLockfile_Call) Return(_a0 ports.Lockfile, _a1 error) *ConfigStore_ReadLockfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConfigStore_ReadLockfile_Call) RunAndReturn(run func(string) (ports.Lockfile, error)) *ConfigStore_ReadLockfile_Call {
	_c.Call.Return(run)
	return _c
}

// WriteConfig provides a mock function with given fields: destDir, cfg
func (_m *ConfigStore) WriteConfig(destDir string, cfg ports.UnsareportConfig) error {
	ret := _m.Called(destDir, cfg)

	if len(ret) == 0 {
		panic("no return value specified for WriteConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, ports.UnsareportConfig) error); ok {
		r0 = rf(destDir, cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConfigStore_WriteConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteConfig'
type ConfigStore_WriteConfig_Call struct {
	*mock.Call
}

// WriteConfig is a helper method to define mock.On call
//   - destDir string
//   - cfg ports.UnsareportConfig
func (_e *ConfigStore_Expecter) WriteConfig(destDir interface{}, cfg interface{}) *ConfigStore_WriteConfig_Call {
	return &ConfigStore_WriteConfig_Call{Call: _e.mock.On("WriteConfig", destDir, cfg)}
}

func (_c *ConfigStore_WriteConfig_Call) Run(run func(destDir string, cfg ports.UnsareportConfig)) *ConfigStore_WriteConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(ports.UnsareportConfig))
	})
	return _c
}

func (_c *ConfigStore_WriteConfig_Call) Return(_a0 error) *ConfigStore_WriteConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConfigStore_WriteConfig_Call) RunAndReturn(run func(string, ports.UnsareportConfig) error) *ConfigStore_WriteConfig_Call {
	_c.Call.Return(run)
	return _c
}

// WriteLockfile provides a mock function with given fields: destDir, lf
func (_m *ConfigStore) WriteLockfile(destDir string, lf ports.Lockfile) error {
	ret := _m.Called(destDir, lf)

	if len(ret) == 0 {
		panic("no return value specified for WriteLockfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, ports.Lockfile) error); ok {
		r0 = rf(destDir, lf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConfigStore_WriteLockfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteLockfile'
type ConfigStore_WriteLockfile_Call struct {
	*mock.Call
}

// WriteLockfile is a helper method to define mock.On call
//   - destDir string
//   - lf ports.Lockfile
func (_e *ConfigStore_Expecter) WriteLockfile(destDir interface{}, lf interface{}) *ConfigStore_WriteLockfile_Call {
	return &ConfigStore_WriteLockfile_Call{Call: _e.mock.On("WriteLockfile", destDir, lf)}
}

func (_c *ConfigStore_WriteLockfile_Call) Run(run func(destDir string, lf ports.Lockfile)) *ConfigStore_WriteLockfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(ports.Lockfile))
	})
	return _c
}

func (_c *ConfigStore_WriteLockfile_Call) Return(_a0 error) *ConfigStore_WriteLockfile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConfigStore_WriteLockfile_Call) RunAndReturn(run func(string, ports.Lockfile) error) *ConfigStore_WriteLockfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewConfigStore creates a new instance of ConfigStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigStore {
	mock := &ConfigStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
