// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	fs "io/fs"

	mock "github.com/stretchr/testify/mock"
)

// FileSystem is an autogenerated mock type for the FileSystem type
type FileSystem struct {
	mock.Mock
}

type FileSystem_Expecter struct {
	mock *mock.Mock
}

func (_m *FileSystem) EXPECT() *FileSystem_Expecter {
	return &FileSystem_Expecter{mock: &_m.Mock}
}

// Chdir provides a mock function with given fields: dir
func (_m *FileSystem) Chdir(dir string) error {
	ret := _m.Called(dir)

	if len(ret) == 0 {
		panic("no return value specified for Chdir")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(dir)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileSystem_Chdir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chdir'
type FileSystem_Chdir_Call struct {
	*mock.Call
}

// Chdir is a helper method to define mock.On call
//   - dir string
func (_e *FileSystem_Expecter) Chdir(dir interface{}) *FileSystem_Chdir_Call {
	return &FileSystem_Chdir_Call{Call: _e.mock.On("Chdir", dir)}
}

func (_c *FileSystem_Chdir_Call) Run(run func(dir string)) *FileSystem_Chdir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *FileSystem_Chdir_Call) Return(_a0 error) *FileSystem_Chdir_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileSystem_Chdir_Call) RunAndReturn(run func(string) error) *FileSystem_Chdir_Call {
	_c.Call.Return(run)
	return _c
}

// CopyFile provides a mock function with given fields: src, dst, perm
func (_m *FileSystem) CopyFile(src string, dst string, perm fs.FileMode) error {
	ret := _m.Called(src, dst, perm)

	if len(ret) == 0 {
		panic("no return value specified for CopyFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, fs.FileMode) error); ok {
		r0 = rf(src, dst, perm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileSystem_CopyFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CopyFile'
type FileSystem_CopyFile_Call struct {
	*mock.Call
}

// CopyFile is a helper method to define mock.On call
//   - src string
//   - dst string
//   - perm fs.FileMode
func (_e *FileSystem_Expecter) CopyFile(src interface{}, dst interface{}, perm interface{}) *FileSystem_CopyFile_Call {
	return &FileSystem_CopyFile_Call{Call: _e.mock.On("CopyFile", src, dst, perm)}
}

func (_c *FileSystem_CopyFile_Call) Run(run func(src string, dst string, perm fs.FileMode)) *FileSystem_CopyFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(fs.FileMode))
	})
	return _c
}

func (_c *FileSystem_CopyFile_Call) Return(_a0 error) *FileSystem_CopyFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileSystem_CopyFile_Call) RunAndReturn(run func(string, string, fs.FileMode) error) *FileSystem_CopyFile_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureDir provides a mock function with given fields: path
func (_m *FileSystem) EnsureDir(path string) error {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for EnsureDir")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileSystem_EnsureDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureDir'
type FileSystem_EnsureDir_Call struct {
	*mock.Call
}

// EnsureDir is a helper method to define mock.On call
//   - path string
func (_e *FileSystem_Expecter) EnsureDir(path interface{}) *FileSystem_EnsureDir_Call {
	return &FileSystem_EnsureDir_Call{Call: _e.mock.On("EnsureDir", path)}
}

func (_c *FileSystem_EnsureDir_Call) Run(run func(path string)) *FileSystem_EnsureDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *FileSystem_EnsureDir_Call) Return(_a0 error) *FileSystem_EnsureDir_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileSystem_EnsureDir_Call) RunAndReturn(run func(string) error) *FileSystem_EnsureDir_Call {
	_c.Call.Return(run)
	return _c
}

// FileExists provides a mock function with given fields: path
func (_m *FileSystem) FileExists(path string) bool {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for FileExists")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// FileSystem_FileExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileExists'
type FileSystem_FileExists_Call struct {
	*mock.Call
}

// FileExists is a helper method to define mock.On call
//   - path string
func (_e *FileSystem_Expecter) FileExists(path interface{}) *FileSystem_FileExists_Call {
	return &FileSystem_FileExists_Call{Call: _e.mock.On("FileExists", path)}
}

func (_c *FileSystem_FileExists_Call) Run(run func(path string)) *FileSystem_FileExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *FileSystem_FileExists_Call) Return(_a0 bool) *FileSystem_FileExists_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileSystem_FileExists_Call) RunAndReturn(run func(string) bool) *FileSystem_FileExists_Call {
	_c.Call.Return(run)
	return _c
}

// Getwd provides a mock function with no fields
func (_m *FileSystem) Getwd() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Getwd")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileSystem_Getwd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Getwd'
type FileSystem_Getwd_Call struct {
	*mock.Call
}

// Getwd is a helper method to define mock.On call
func (_e *FileSystem_Expecter) Getwd() *FileSystem_Getwd_Call {
	return &FileSystem_Getwd_Call{Call: _e.mock.On("Getwd")}
}

func (_c *FileSystem_Getwd_Call) Run(run func()) *FileSystem_Getwd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FileSystem_Getwd_Call) Return(_a0 string, _a1 error) *FileSystem_Getwd_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileSystem_Getwd_Call) RunAndReturn(run func() (string, error)) *FileSystem_Getwd_Call {
	_c.Call.Return(run)
	return _c
}

// ReadDir provides a mock function with given fields: dirname
func (_m *FileSystem) ReadDir(dirname string) ([]fs.DirEntry, error) {
	ret := _m.Called(dirname)

	if len(ret) == 0 {
		panic("no return value specified for ReadDir")
	}

	var r0 []fs.DirEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]fs.DirEntry, error)); ok {
		return rf(dirname)
	}
	if rf, ok := ret.Get(0).(func(string) []fs.DirEntry); ok {
		r0 = rf(dirname)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]fs.DirEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(dirname)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileSystem_ReadDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDir'
type FileSystem_ReadDir_Call struct {
	*mock.Call
}

// ReadDir is a helper method to define mock.On call
//   - dirname string
func (_e *FileSystem_Expecter) ReadDir(dirname interface{}) *FileSystem_ReadDir_Call {
	return &FileSystem_ReadDir_Call{Call: _e.mock.On("ReadDir", dirname)}
}

func (_c *FileSystem_ReadDir_Call) Run(run func(dirname string)) *FileSystem_ReadDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *FileSystem_ReadDir_Call) Return(_a0 []fs.DirEntry, _a1 error) *FileSystem_ReadDir_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileSystem_ReadDir_Call) RunAndReturn(run func(string) ([]fs.DirEntry, error)) *FileSystem_ReadDir_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function with given fields: path
func (_m *FileSystem) ReadFile(path string) ([]byte, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileSystem_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type FileSystem_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - path string
func (_e *FileSystem_Expecter) ReadFile(path interface{}) *FileSystem_ReadFile_Call {
	return &FileSystem_ReadFile_Call{Call: _e.mock.On("ReadFile", path)}
}

func (_c *FileSystem_ReadFile_Call) Run(run func(path string)) *FileSystem_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *FileSystem_ReadFile_Call) Return(_a0 []byte, _a1 error) *FileSystem_ReadFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileSystem_ReadFile_Call) RunAndReturn(run func(string) ([]byte, error)) *FileSystem_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: path
func (_m *FileSystem) Remove(path string) error {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileSystem_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type FileSystem_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - path string
func (_e *FileSystem_Expecter) Remove(path interface{}) *FileSystem_Remove_Call {
	return &FileSystem_Remove_Call{Call: _e.mock.On("Remove", path)}
}

func (_c *FileSystem_Remove_Call) Run(run func(path string)) *FileSystem_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *FileSystem_Remove_Call) Return(_a0 error) *FileSystem_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileSystem_Remove_Call) RunAndReturn(run func(string) error) *FileSystem_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// SameContent provides a mock function with given fields: a, b
func (_m *FileSystem) SameContent(a []byte, b []byte) bool {
	ret := _m.Called(a, b)

	if len(ret) == 0 {
		panic("no return value specified for SameContent")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func([]byte, []byte) bool); ok {
		r0 = rf(a, b)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// FileSystem_SameContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SameContent'
type FileSystem_SameContent_Call struct {
	*mock.Call
}

// SameContent is a helper method to define mock.On call
//   - a []byte
//   - b []byte
func (_e *FileSystem_Expecter) SameContent(a interface{}, b interface{}) *FileSystem_SameContent_Call {
	return &FileSystem_SameContent_Call{Call: _e.mock.On("SameContent", a, b)}
}

func (_c *FileSystem_SameContent_Call) Run(run func(a []byte, b []byte)) *FileSystem_SameContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].([]byte))
	})
	return _c
}

func (_c *FileSystem_SameContent_Call) Return(_a0 bool) *FileSystem_SameContent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileSystem_SameContent_Call) RunAndReturn(run func([]byte, []byte) bool) *FileSystem_SameContent_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function with given fields: name
func (_m *FileSystem) Stat(name string) (fs.FileInfo, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 fs.FileInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (fs.FileInfo, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) fs.FileInfo); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.FileInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileSystem_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type FileSystem_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - name string
func (_e *FileSystem_Expecter) Stat(name interface{}) *FileSystem_Stat_Call {
	return &FileSystem_Stat_Call{Call: _e.mock.On("Stat", name)}
}

func (_c *FileSystem_Stat_Call) Run(run func(name string)) *FileSystem_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *FileSystem_Stat_Call) Return(_a0 fs.FileInfo, _a1 error) *FileSystem_Stat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileSystem_Stat_Call) RunAndReturn(run func(string) (fs.FileInfo, error)) *FileSystem_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFileAtomic provides a mock function with given fields: path, data, perm
func (_m *FileSystem) WriteFileAtomic(path string, data []byte, perm fs.FileMode) error {
	ret := _m.Called(path, data, perm)

	if len(ret) == 0 {
		panic("no return value specified for WriteFileAtomic")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte, fs.FileMode) error); ok {
		r0 = rf(path, data, perm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileSystem_WriteFileAtomic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFileAtomic'
type FileSystem_WriteFileAtomic_Call struct {
	*mock.Call
}

// WriteFileAtomic is a helper method to define mock.On call
//   - path string
//   - data []byte
//   - perm fs.FileMode
func (_e *FileSystem_Expecter) WriteFileAtomic(path interface{}, data interface{}, perm interface{}) *FileSystem_WriteFileAtomic_Call {
	return &FileSystem_WriteFileAtomic_Call{Call: _e.mock.On("WriteFileAtomic", path, data, perm)}
}

func (_c *FileSystem_WriteFileAtomic_Call) Run(run func(path string, data []byte, perm fs.FileMode)) *FileSystem_WriteFileAtomic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte), args[2].(fs.FileMode))
	})
	return _c
}

func (_c *FileSystem_WriteFileAtomic_Call) Return(_a0 error) *FileSystem_WriteFileAtomic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileSystem_WriteFileAtomic_Call) RunAndReturn(run func(string, []byte, fs.FileMode) error) *FileSystem_WriteFileAtomic_Call {
	_c.Call.Return(run)
	return _c
}

// NewFileSystem creates a new instance of FileSystem. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileSystem(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileSystem {
	mock := &FileSystem{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
