// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	ports "github.com/UNSAReport/UNSAReport/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// Renderer is an autogenerated mock type for the Renderer type
type Renderer struct {
	mock.Mock
}

type Renderer_Expecter struct {
	mock *mock.Mock
}

func (_m *Renderer) EXPECT() *Renderer_Expecter {
	return &Renderer_Expecter{mock: &_m.Mock}
}

// Render provides a mock function with given fields: ctx, resultPath, commands, flags, cfg
func (_m *Renderer) Render(ctx context.Context, resultPath string, commands []ports.CaptureCommand, flags []string, cfg ports.CaptureConfig) (string, error) {
	ret := _m.Called(ctx, resultPath, commands, flags, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Render")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []ports.CaptureCommand, []string, ports.CaptureConfig) (string, error)); ok {
		return rf(ctx, resultPath, commands, flags, cfg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []ports.CaptureCommand, []string, ports.CaptureConfig) string); ok {
		r0 = rf(ctx, resultPath, commands, flags, cfg)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []ports.CaptureCommand, []string, ports.CaptureConfig) error); ok {
		r1 = rf(ctx, resultPath, commands, flags, cfg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Renderer_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type Renderer_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - ctx context.Context
//   - resultPath string
//   - commands []ports.CaptureCommand
//   - flags []string
//   - cfg ports.CaptureConfig
func (_e *Renderer_Expecter) Render(ctx interface{}, resultPath interface{}, commands interface{}, flags interface{}, cfg interface{}) *Renderer_Render_Call {
	return &Renderer_Render_Call{Call: _e.mock.On("Render", ctx, resultPath, commands, flags, cfg)}
}

func (_c *Renderer_Render_Call) Run(run func(ctx context.Context, resultPath string, commands []ports.CaptureCommand, flags []string, cfg ports.CaptureConfig)) *Renderer_Render_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]ports.CaptureCommand), args[3].([]string), args[4].(ports.CaptureConfig))
	})
	return _c
}

func (_c *Renderer_Render_Call) Return(_a0 string, _a1 error) *Renderer_Render_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Renderer_Render_Call) RunAndReturn(run func(context.Context, string, []ports.CaptureCommand, []string, ports.CaptureConfig) (string, error)) *Renderer_Render_Call {
	_c.Call.Return(run)
	return _c
}

// NewRenderer creates a new instance of Renderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Renderer {
	mock := &Renderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
