// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	ports "github.com/UNSAReport/UNSAReport/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// TemplateRegistry is an autogenerated mock type for the TemplateRegistry type
type TemplateRegistry struct {
	mock.Mock
}

type TemplateRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *TemplateRegistry) EXPECT() *TemplateRegistry_Expecter {
	return &TemplateRegistry_Expecter{mock: &_m.Mock}
}

// GetTemplate provides a mock function with given fields: name
func (_m *TemplateRegistry) GetTemplate(name string) (ports.TemplateInfo, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplate")
	}

	var r0 ports.TemplateInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (ports.TemplateInfo, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) ports.TemplateInfo); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(ports.TemplateInfo)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TemplateRegistry_GetTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemplate'
type TemplateRegistry_GetTemplate_Call struct {
	*mock.Call
}

// GetTemplate is a helper method to define mock.On call
//   - name string
func (_e *TemplateRegistry_Expecter) GetTemplate(name interface{}) *TemplateRegistry_GetTemplate_Call {
	return &TemplateRegistry_GetTemplate_Call{Call: _e.mock.On("GetTemplate", name)}
}

func (_c *TemplateRegistry_GetTemplate_Call) Run(run func(name string)) *TemplateRegistry_GetTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TemplateRegistry_GetTemplate_Call) Return(_a0 ports.TemplateInfo, _a1 error) *TemplateRegistry_GetTemplate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TemplateRegistry_GetTemplate_Call) RunAndReturn(run func(string) (ports.TemplateInfo, error)) *TemplateRegistry_GetTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// GetTemplateVersion provides a mock function with given fields: name, rangeSpec
func (_m *TemplateRegistry) GetTemplateVersion(name string, rangeSpec string) (ports.TemplateInfo, error) {
	ret := _m.Called(name, rangeSpec)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplateVersion")
	}

	var r0 ports.TemplateInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (ports.TemplateInfo, error)); ok {
		return rf(name, rangeSpec)
	}
	if rf, ok := ret.Get(0).(func(string, string) ports.TemplateInfo); ok {
		r0 = rf(name, rangeSpec)
	} else {
		r0 = ret.Get(0).(ports.TemplateInfo)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(name, rangeSpec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TemplateRegistry_GetTemplateVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemplateVersion'
type TemplateRegistry_GetTemplateVersion_Call struct {
	*mock.Call
}

// GetTemplateVersion is a helper method to define mock.On call
//   - name string
//   - rangeSpec string
func (_e *TemplateRegistry_Expecter) GetTemplateVersion(name interface{}, rangeSpec interface{}) *TemplateRegistry_GetTemplateVersion_Call {
	return &TemplateRegistry_GetTemplateVersion_Call{Call: _e.mock.On("GetTemplateVersion", name, rangeSpec)}
}

func (_c *TemplateRegistry_GetTemplateVersion_Call) Run(run func(name string, rangeSpec string)) *TemplateRegistry_GetTemplateVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *TemplateRegistry_GetTemplateVersion_Call) Return(_a0 ports.TemplateInfo, _a1 error) *TemplateRegistry_GetTemplateVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TemplateRegistry_GetTemplateVersion_Call) RunAndReturn(run func(string, string) (ports.TemplateInfo, error)) *TemplateRegistry_GetTemplateVersion_Call {
	_c.Call.Return(run)
	return _c
}

// ListTemplates provides a mock function with no fields
func (_m *TemplateRegistry) ListTemplates() ([]ports.TemplateInfo, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListTemplates")
	}

	var r0 []ports.TemplateInfo
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]ports.TemplateInfo, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []ports.TemplateInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.TemplateInfo)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TemplateRegistry_ListTemplates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTemplates'
type TemplateRegistry_ListTemplates_Call struct {
	*mock.Call
}

// ListTemplates is a helper method to define mock.On call
func (_e *TemplateRegistry_Expecter) ListTemplates() *TemplateRegistry_ListTemplates_Call {
	return &TemplateRegistry_ListTemplates_Call{Call: _e.mock.On("ListTemplates")}
}

func (_c *TemplateRegistry_ListTemplates_Call) Run(run func()) *TemplateRegistry_ListTemplates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TemplateRegistry_ListTemplates_Call) Return(_a0 []ports.TemplateInfo, _a1 error) *TemplateRegistry_ListTemplates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TemplateRegistry_ListTemplates_Call) RunAndReturn(run func() ([]ports.TemplateInfo, error)) *TemplateRegistry_ListTemplates_Call {
	_c.Call.Return(run)
	return _c
}

// NewTemplateRegistry creates a new instance of TemplateRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTemplateRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *TemplateRegistry {
	mock := &TemplateRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
