// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TemplateFetcher is an autogenerated mock type for the TemplateFetcher type
type TemplateFetcher struct {
	mock.Mock
}

type TemplateFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *TemplateFetcher) EXPECT() *TemplateFetcher_Expecter {
	return &TemplateFetcher_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function with given fields: ctx, repo, ref, templatePath
func (_m *TemplateFetcher) Fetch(ctx context.Context, repo string, ref string, templatePath string) (map[string][]byte, error) {
	ret := _m.Called(ctx, repo, ref, templatePath)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 map[string][]byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (map[string][]byte, error)); ok {
		return rf(ctx, repo, ref, templatePath)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) map[string][]byte); ok {
		r0 = rf(ctx, repo, ref, templatePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, repo, ref, templatePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TemplateFetcher_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type TemplateFetcher_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - ref string
//   - templatePath string
func (_e *TemplateFetcher_Expecter) Fetch(ctx interface{}, repo interface{}, ref interface{}, templatePath interface{}) *TemplateFetcher_Fetch_Call {
	return &TemplateFetcher_Fetch_Call{Call: _e.mock.On("Fetch", ctx, repo, ref, templatePath)}
}

func (_c *TemplateFetcher_Fetch_Call) Run(run func(ctx context.Context, repo string, ref string, templatePath string)) *TemplateFetcher_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *TemplateFetcher_Fetch_Call) Return(_a0 map[string][]byte, _a1 error) *TemplateFetcher_Fetch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TemplateFetcher_Fetch_Call) RunAndReturn(run func(context.Context, string, string, string) (map[string][]byte, error)) *TemplateFetcher_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// FetchRaw provides a mock function with given fields: ctx, repo, ref, path
func (_m *TemplateFetcher) FetchRaw(ctx context.Context, repo string, ref string, path string) ([]byte, error) {
	ret := _m.Called(ctx, repo, ref, path)

	if len(ret) == 0 {
		panic("no return value specified for FetchRaw")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) ([]byte, error)); ok {
		return rf(ctx, repo, ref, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) []byte); ok {
		r0 = rf(ctx, repo, ref, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, repo, ref, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TemplateFetcher_FetchRaw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchRaw'
type TemplateFetcher_FetchRaw_Call struct {
	*mock.Call
}

// FetchRaw is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - ref string
//   - path string
func (_e *TemplateFetcher_Expecter) FetchRaw(ctx interface{}, repo interface{}, ref interface{}, path interface{}) *TemplateFetcher_FetchRaw_Call {
	return &TemplateFetcher_FetchRaw_Call{Call: _e.mock.On("FetchRaw", ctx, repo, ref, path)}
}

func (_c *TemplateFetcher_FetchRaw_Call) Run(run func(ctx context.Context, repo string, ref string, path string)) *TemplateFetcher_FetchRaw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *TemplateFetcher_FetchRaw_Call) Return(_a0 []byte, _a1 error) *TemplateFetcher_FetchRaw_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TemplateFetcher_FetchRaw_Call) RunAndReturn(run func(context.Context, string, string, string) ([]byte, error)) *TemplateFetcher_FetchRaw_Call {
	_c.Call.Return(run)
	return _c
}

// LoadLocal provides a mock function with given fields: dir
func (_m *TemplateFetcher) LoadLocal(dir string) (map[string][]byte, error) {
	ret := _m.Called(dir)

	if len(ret) == 0 {
		panic("no return value specified for LoadLocal")
	}

	var r0 map[string][]byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (map[string][]byte, error)); ok {
		return rf(dir)
	}
	if rf, ok := ret.Get(0).(func(string) map[string][]byte); ok {
		r0 = rf(dir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(dir)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TemplateFetcher_LoadLocal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadLocal'
type TemplateFetcher_LoadLocal_Call struct {
	*mock.Call
}

// LoadLocal is a helper method to define mock.On call
//   - dir string
func (_e *TemplateFetcher_Expecter) LoadLocal(dir interface{}) *TemplateFetcher_LoadLocal_Call {
	return &TemplateFetcher_LoadLocal_Call{Call: _e.mock.On("LoadLocal", dir)}
}

func (_c *TemplateFetcher_LoadLocal_Call) Run(run func(dir string)) *TemplateFetcher_LoadLocal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TemplateFetcher_LoadLocal_Call) Return(_a0 map[string][]byte, _a1 error) *TemplateFetcher_LoadLocal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TemplateFetcher_LoadLocal_Call) RunAndReturn(run func(string) (map[string][]byte, error)) *TemplateFetcher_LoadLocal_Call {
	_c.Call.Return(run)
	return _c
}

// NewTemplateFetcher creates a new instance of TemplateFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTemplateFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *TemplateFetcher {
	mock := &TemplateFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
